options:
  logging: CLOUD_LOGGING_ONLY  # Specify how logging should be handled

steps:
  # Fetch the service account key from GCS
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Download the service account key from GCS
        echo "Downloading service account key..."
        gsutil cp gs://mnkcloud/service-account-key.json /tmp/service-account-key.json
        
        # Verify the key file
        echo "Listing files in /tmp directory..."
        ls -l /tmp
        
        echo "Displaying contents of the service account key file..."
        cat /tmp/service-account-key.json
        
        # Activate service account using the key file
        echo "Activating service account..."
        gcloud auth activate-service-account --key-file=/tmp/service-account-key.json

  # Get credentials for the existing Kubernetes cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get credentials for the existing cluster
        gcloud container clusters get-credentials geminiai --zone us-central1-a

  # Create Docker registry secret
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create Docker registry secret
        kubectl create secret docker-registry regcred \
          --docker-server=gcr.io \
          --docker-username=_json_key \
          --docker-password="$(cat /tmp/service-account-key.json)" \
          --docker-email=mounika8036@mounika8036-426015.iam.gserviceaccount.com

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/geminiai:$SHORT_SHA', '.']

  # Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/geminiai:$SHORT_SHA']

  # Apply Kubernetes deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', './deployment.yaml']
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-a', 'CLOUDSDK_CONTAINER_CLUSTER=geminiai']

  # Apply Kubernetes service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', './service.yaml']
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-a', 'CLOUDSDK_CONTAINER_CLUSTER=geminiai']

timeout: 1200s  # Timeout for the build process
